# Generated by Django 3.1.3 on 2020-11-22 00:15

from django.db import migrations
from django.contrib.auth.models import Group

USER_GROUPS = ['admins', 'users', 'rooms']
def create_user_groups(*args, **kwargs):
    for group in USER_GROUPS:
        Group.objects.get_or_create(name=group)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
